// Cache invalidation is intentionally disabled.
// The dashboard doesn't generate analysis at all anymore — the separate
// stockBot_AI_Insight worker writes `ai-analysis:{date}` on its own cron schedule.
// Deleting the key here wouldn't trigger a new Claude call; it would just make the
// dashboard show "not generated yet" until the worker's next scheduled run.
export async function POST() {
  return Response.json(
    { message: "Cache invalidation is not supported. Analysis is generated by a separate scheduled worker, not this app." },
    { status: 405 }
  );
}
